name: wedding_bingo
description: Bingo app for the bug wedding

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

# `flutter pub upgrade --major-versions`
# `flutter pub outdated`
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - images/jared.jpg
    - images/brianna.jpg
    - images/nathan.jpg
    - images/steve.jpg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
