name: wedding_bingo
description: Bingo app for the bug wedding

publish_to: 'none'

version: 0.5.0+10

environment:
  sdk: '>=2.17.0 <3.0.0'

# `flutter pub upgrade --major-versions`
# `flutter pub outdated`
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^4.0.1
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.4
  lottie: ^1.3.0
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/json/

  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/JosefinSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/JosefinSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/JosefinSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/JosefinSans-Light.ttf
          weight: 300
        - asset: assets/fonts/JosefinSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/JosefinSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/JosefinSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/JosefinSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/JosefinSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/JosefinSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/JosefinSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/JosefinSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/JosefinSans-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Marcellus
      fonts:
        - asset: assets/fonts/Marcellus-Regular.ttf
          weight: 400
